<a href="https://colab.research.google.com/github/ola-sumbo/Hamoye-and-ML-with-Ude/blob/master/Data_Wrangling_Hamoye1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
cell_data = pd.read_csv('https://raw.githubusercontent.com/zalihat/cell_phone_dataset/master/cell_phones.csv')
pop_data = pd.read_csv('https://raw.githubusercontent.com/zalihat/cell_phone_dataset/master/population1.csv')
geo_code = pd.read_csv('https://raw.githubusercontent.com/open-numbers/ddf--gapminder--systema_globalis/master/ddf--entities--geo--country.csv')

**Joining the data**

In [3]:
merged = cell_data.merge(pop_data, how='inner', on = ['Country', 'year'])
merged.shape

(11640, 4)

In [4]:
merged.head()

       Country  year  cell_phones_total  population
0  Afghanistan  1960                0.0     9000000
1  Afghanistan  1961                0.0     9170000
2  Afghanistan  1962                0.0     9350000
3  Afghanistan  1963                0.0     9540000
4  Afghanistan  1964                0.0     9740000

In [8]:
# renaming columns in geodataframe
geo_codes = geo_code.rename(columns={'country':'geo', 'name':'Country'})
geo_code.head()

    geo g77_and_oecd_countries  ... world_4region        world_6region
0  abkh                 others  ...        europe  europe_central_asia
1   abw                 others  ...      americas              america
2   afg                    g77  ...          asia           south_asia
3   ago                    g77  ...        africa   sub_saharan_africa
4   aia                 others  ...      americas              america

[5 rows x 21 columns]

In [91]:
from IPython.display import display
from IPython.display import Image
final = pd.merge(geo_codes, merged, on='Country', how='inner')
final.shape

(11640, 24)

In [92]:
#final = pd.concat([merged, geo_codes], axis=1)
#final = pd.DataFrame(final)
#final.shape
final.head()

   geo g77_and_oecd_countries  ... cell_phones_total population
0  afg                    g77  ...               0.0    9000000
1  afg                    g77  ...               0.0    9170000
2  afg                    g77  ...               0.0    9350000
3  afg                    g77  ...               0.0    9540000
4  afg                    g77  ...               0.0    9740000

[5 rows x 24 columns]

**Make Features**

In [93]:
final['cell_phones_total']/final['population']

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...
11635    0.927536
11636    0.921429
11637    0.992958
11638    0.895833
11639    0.904110
Length: 11640, dtype: float64

In [43]:
final.isna().count()
finals = final.drop_duplicates()

In [94]:
final['population'].sum()/final['cell_phones_total'].sum()

3.44134387900734

In [192]:
final[final.Country == 'United States']
final.groupby(['Country']).agg({'population': 'sum', 'cell_phones_total':'sum',}, sorted)

                                 population  cell_phones_total
Country
Afghanistan                      1101860000       2.119150e+08
Albania                           163580000       4.581600e+07
Algeria                          1518400000       5.481060e+08
Andorra                             3093200       1.298474e+06
Angola                            829190000       1.558799e+08
Antigua and Barbuda                 4255900       2.023000e+06
Argentina                        1938300000       8.595809e+08
Armenia                           174750000       4.233059e+07
Australia                        1023200000       4.472235e+08
Austria                           473290000       2.167054e+08
Azerbaijan                        425000000       1.314525e+08
Bahamas                            15280000       5.611260e+06
Bahrain                            37168000       2.981395e+07
Bangladesh                       6218900000       1.404287e+09
Barbados                           15623000       5.200812e+06
Belarus                           566800000       1.389088e+08
Belgium                           610140000       2.211696e+08
Belize                             12457200       3.024732e+06
Benin                             342620000       1.017621e+08
Bhutan                             29657000       7.026460e+06
Bolivia                           425770000       1.149592e+08
Bosnia and Herzegovina            230410000       5.027570e+07
Botswana                           77140000       4.024820e+07
Brazil                           8710600000       3.015405e+09
Brunei                             15466100       7.678300e+06
Bulgaria                          492060000       1.537100e+08
Burkina Faso                      601110000       1.456802e+08
Burundi                           347550000       4.310560e+07
Cambodia                          602050000       2.002502e+08
Cameroon                          770990000       1.895851e+08
Canada                           1648100000       4.878884e+08
Cape Verde                         21699000       6.470010e+06
Central African Republic          177770000       1.423184e+07
Chad                              431880000       5.855370e+07
Chile                             799150000       3.374405e+08
China                           66722000000       1.689864e+10
Colombia                         1978600000       7.561348e+08
Comoros                            26609000       4.157580e+06
Congo, Dem. Rep.                 2397300000       3.256716e+08
Congo, Rep.                       157870000       5.086039e+07
Costa Rica                        189190000       7.919323e+07
Cote d'Ivoire                     754080000       2.913697e+08
Croatia                           267550000       7.966828e+07
Cuba                              606650000       3.348266e+07
Cyprus                             49621000       1.863005e+07
Czech Republic                    614120000       2.391502e+08
Denmark                           312170000       1.334590e+08
Djibouti                           31003300       3.005943e+06
Dominica                            4228100       1.289377e+06
Dominican Republic                422940000       1.270959e+08
Ecuador                           622660000       2.123071e+08
Egypt                            3451800000       1.110969e+09
El Salvador                       300900000       1.138525e+08
Equatorial Guinea                  32608000       5.576558e+06
Eritrea                           129050000       3.636700e+06
Estonia                            83670000       3.214109e+07
Eswatini                           46052000       9.524700e+06
Ethiopia                         3280100000       2.394477e+08
Fiji                               41852000       9.907500e+06
Finland                           299490000       1.451748e+08
France                           3384900000       1.161355e+09
Gabon                              63583000       3.052594e+07
Gambia                             63936000       2.468680e+07
Georgia                           276540000       6.476745e+07
Germany                          4766100000       1.828493e+09
Ghana                             960600000       3.602952e+08
Greece                            598400000       2.345540e+08
Grenada                             5947900       1.519836e+06
Guatemala                         586700000       2.599807e+08
Guinea                            413110000       9.799702e+07
Guinea-Bissau                      63895000       1.319258e+07
Guyana                             44152000       7.201731e+06
Haiti                             429750000       6.682150e+07
Honduras                          317250000       1.034662e+08
Hungary                           615020000       1.989671e+08
Iceland                            15377000       7.174560e+06
India                           52845000000       1.144649e+10
Indonesia                       10682000000       3.791016e+09
Iran                             3121100000       9.151771e+08
Iraq                             1163300000       3.411540e+08
Ireland                           218110000       9.257328e+07
Israel                            292670000       1.813068e+08
Italy                            3385300000       1.662439e+09
Jamaica                           141880000       4.885468e+07
Japan                            7131600000       2.506760e+09
Jordan                            252177000       1.235936e+08
Kazakhstan                        896730000       3.272742e+08
Kenya                            1533280000       4.378577e+08
Kiribati                            4444700       3.550630e+05
Kuwait                            110237000       8.014970e+07
Kyrgyz Republic                   253210000       8.602602e+07
Lao                               262010000       5.127146e+07
Latvia                            140940000       4.020979e+07
Lebanon                           212070000       5.332200e+07
Lesotho                            95139000       1.739619e+07
Liberia                           147270000       2.427820e+07
Libya                             251840000       1.008070e+08
Liechtenstein                       1714200       6.717000e+05
Lithuania                         197000000       7.880082e+07
Luxembourg                         24749000       1.387398e+07
Madagascar                        785990000       9.741870e+07
Malawi                            558440000       6.682278e+07
Malaysia                         1127710000       5.952045e+08
Maldives                           14340600       8.950790e+06
Mali                              591060000       1.763913e+08
Malta                              21961000       8.771580e+06
Marshall Islands                    2410900       5.255300e+04
Mauritania                        133270000       4.719130e+07
Mauritius                          62335000       2.102276e+07
Mexico                           4948700000       1.548032e+09
Micronesia, Fed. Sts.               5185100       3.205700e+05
Moldova                           238420000       4.617313e+07
Monaco                              1781000       5.432200e+05
Mongolia                          122378000       4.160253e+07
Montenegro                         35334000       1.571600e+07
Morocco                          1453900000       5.411699e+08
Mozambique                        926770000       1.348045e+08
Myanmar                          2366500000       2.437381e+08
Namibia                            86742000       3.061914e+07
Nauru                                517820       5.600000e+04
Nepal                            1150300000       2.332108e+08
Netherlands                       888700000       3.735093e+08
New Zealand                       211740000       8.589470e+07
Nicaragua                         246820000       7.861036e+07
Niger                             584010000       6.079673e+07
Nigeria                          6189900000       1.427575e+09
North Korea                      1177500000       1.908130e+07
North Macedonia                   114880000       3.187826e+07
Norway                            259980000       1.068296e+08
Oman                              116561000       7.530231e+07
Pakistan                         6865900000       1.621640e+09
Palau                                906370       1.676000e+05
Palestine                         148310000       3.727608e+07
Panama                            151760000       8.082240e+07
Papua New Guinea                  292570000       2.762783e+07
Paraguay                          256790000       9.260445e+07
Peru                             1286800000       3.956570e+08
Philippines                      3806300000       1.525288e+09
Poland                           2167500000       8.008008e+08
Portugal                          587640000       2.365992e+08
Qatar                              44874400       4.093889e+07
Romania                          1283500000       3.604336e+08
Russia                           8381000000       3.254368e+09
Rwanda                            403980000       7.938240e+07
Samoa                               9741000       9.872760e+05
San Marino                          1475800       5.782300e+05
Sao Tome and Principe               7390300       1.666450e+06
Saudi Arabia                      978120000       6.585209e+08
Senegal                           488850000       1.609510e+08
Serbia                            533170000       1.364100e+08
Seychelles                          4311300       2.155730e+06
Sierra Leone                      262250000       4.993480e+07
Singapore                         201040000       1.325117e+08
Slovak Republic                   304180000       1.081907e+08
Slovenia                          113560000       4.189192e+07
Solomon Islands                    20084000       3.774237e+06
Somalia                           455170000       4.657100e+07
South Africa                     2197200000       1.077507e+09
South Korea                      2479800000       1.013927e+09
South Sudan                       355100000       2.339000e+07
Spain                            2364200000       9.518840e+08
Sri Lanka                         990670000       2.560966e+08
St. Kitts and Nevis                 2744000       9.789450e+05
St. Lucia                           8196300       2.710224e+06
St. Vincent and the Grenadines      6100800       1.859244e+06
Sudan                            1302710000       3.177526e+08
Suriname                           25493000       1.034434e+07
Sweden                            518340000       2.316428e+08
Switzerland                       409760000       1.846840e+08
Syria                             746850000       1.784940e+08
Tajikistan                        311470000       7.543506e+07
Tanzania                         1666000000       3.957760e+08
Thailand                         3176800000       1.364323e+09
Timor-Leste                        47663000       1.175020e+07
Togo                              243380000       5.319650e+07
Tonga                               5541100       9.647580e+05
Trinidad and Tobago                69638000       2.935597e+07
Tunisia                           475830000       1.822241e+08
Turkey                           3213800000       1.147214e+09
Turkmenistan                      219560000       5.760663e+07
Tuvalu                               500390       4.213000e+04
Uganda                           1184130000       2.051072e+08
Ukraine                          2871200000       8.465683e+08
United Arab Emirates              185347400       2.191870e+08
United Kingdom                   3503600000       1.396025e+09
United States                   15335000000       5.458164e+09
Uruguay                           184640000       6.765421e+07
Uzbekistan                       1211040000       2.748721e+08
Vanuatu                             9401600       2.120681e+06
Venezuela                        1169130000       4.201561e+08
Vietnam                          3955300000       1.528051e+09
Yemen                             824450000       1.599800e+08
Zambia                            517170000       1.286192e+08
Zimbabwe                          564170000       1.310737e+08

In [164]:
popagg = final.groupby(['Country','year']).agg({'population': 'sum'})
cellagg = final.groupby(['Country','year']).agg({'cell_phones_total':'sum'})

ns = cellagg['cell_phones_total']/popagg['population']
ns.tail(500)
#pd.options.display.max_rows =2000

Country        year
United States  2000    0.386525
               2001    0.452632
               2002    0.494774
               2003    0.555172
               2004    0.633562
               2005    0.691525
               2006    0.771812
               2007    0.827243
               2008    0.861386
               2009    0.895425
               2010    0.922330
               2011    0.951923
               2012    0.971338
               2013    0.984177
               2014    1.115987
               2015    1.190031
               2016    1.226006
               2017    1.230769
               2018    1.290520
               2019    0.000000
Uruguay        1960    0.000000
               1961    0.000000
               1962    0.000000
               1963    0.000000
               1964    0.000000
               1965    0.000000
               1966    0.000000
               1967    0.000000
               1968    0.000000
               1969    0.000000
               1970    0.000000
               1971    0.000000
               1972    0.000000
               1973    0.000000
               1974    0.000000
               1975    0.000000
               1976    0.000000
               1977    0.000000
               1978    0.000000
               1979    0.000000
               1980    0.000000
               1981    0.000000
               1982    0.000000
               1983    0.000000
               1984    0.000000
               1985    0.000000
               1986    0.000000
               1987    0.000000
               1988    0.000000
               1989    0.000000
               1990    0.000000
               1991    0.000000
               1992    0.000543
               1993    0.001563
               1994    0.002134
               1995    0.012391
               1996    0.024185
               1997    0.030336
               1998    0.045897
               1999    0.096375
               2000    0.123795
               2001    0.156156
               2002    0.154354
               2003    0.150000
               2004    0.180723
               2005    0.346386
               2006    0.699700
               2007    0.900901
               2008    1.050898
               2009    1.226866
               2010    1.321429
               2011    1.412463
               2012    1.479290
               2013    1.554572
               2014    1.617647
               2015    1.516129
               2016    1.497076
               2017    1.482558
               2018    1.498551
               2019    1.381503
Uzbekistan     1960    0.000000
               1961    0.000000
               1962    0.000000
               1963    0.000000
               1964    0.000000
               1965    0.000000
               1966    0.000000
               1967    0.000000
               1968    0.000000
               1969    0.000000
               1970    0.000000
               1971    0.000000
               1972    0.000000
               1973    0.000000
               1974    0.000000
               1975    0.000000
               1976    0.000000
               1977    0.000000
               1978    0.000000
               1979    0.000000
               1980    0.000000
               1981    0.000000
               1982    0.000000
               1983    0.000000
               1984    0.000000
               1985    0.000000
               1986    0.000000
               1987    0.000000
               1988    0.000000
               1989    0.000000
               1990    0.000000
               1991    0.000000
               1992    0.000000
               1993    0.000023
               1994    0.000040
               1995    0.000164
               1996    0.000410
               1997    0.000729
               1998    0.001117
               1999    0.001656
               2000    0.002141
               2001    0.005100
               2002    0.007362
               2003    0.012490
               2004    0.020843
               2005    0.027273
               2006    0.094403
               2007    0.209191
               2008    0.449275
               2009    0.583630
               2010    0.736842
               2011    0.875862
               2012    0.690476
               2013    0.719064
               2014    0.710526
               2015    0.705502
               2016    0.742038
               2017    0.759375
               2018    0.713846
               2019    1.012121
Vanuatu        1960    0.000000
               1961    0.000000
               1962    0.000000
               1963    0.000000
               1964    0.000000
               1965    0.000000
               1966    0.000000
               1967    0.000000
               1968    0.000000
               1969    0.000000
               1970    0.000000
               1971    0.000000
               1972    0.000000
               1973    0.000000
               1974    0.000000
               1975    0.000000
               1976    0.000000
               1977    0.000000
               1978    0.000000
               1979    0.000000
               1980    0.000000
               1981    0.000000
               1982    0.000000
               1983    0.000000
               1984    0.000000
               1985    0.000000
               1986    0.000000
               1987    0.000000
               1988    0.000000
               1989    0.000000
               1990    0.000000
               1991    0.000000
               1992    0.000000
               1993    0.000000
               1994    0.000390
               1995    0.000720
               1996    0.000895
               1997    0.001183
               1998    0.001236
               1999    0.001657
               2000    0.001973
               2001    0.001852
               2002    0.025258
               2003    0.039196
               2004    0.051471
               2005    0.060766
               2006    0.070093
               2007    0.118721
               2008    0.160000
               2009    0.573913
               2010    0.720339
               2011    0.563786
               2012    0.584000
               2013    0.494163
               2014    0.590909
               2015    0.645756
               2016    0.787770
               2017    0.800000
               2018    0.856655
               2019    0.883333
Venezuela      1960    0.000000
               1961    0.000000
               1962    0.000000
               1963    0.000000
               1964    0.000000
               1965    0.000000
               1966    0.000000
               1967    0.000000
               1968    0.000000
               1969    0.000000
               1970    0.000000
               1971    0.000000
               1972    0.000000
               1973    0.000000
               1974    0.000000
               1975    0.000000
               1976    0.000000
               1977    0.000000
               1978    0.000000
               1979    0.000000
               1980    0.000000
               1981    0.000000
               1982    0.000000
               1983    0.000000
               1984    0.000000
               1985    0.000000
               1986    0.000000
               1987    0.000000
               1988    0.000096
               1989    0.000192
               1990    0.000379
               1991    0.000826
               1992    0.003816
               1993    0.008714
               1994    0.014837
               1995    0.018447
               1996    0.025982
               1997    0.046930
               1998    0.086266
               1999    0.159494
               2000    0.225207
               2001    0.263008
               2002    0.260558
               2003    0.274219
               2004    0.323846
               2005    0.473485
               2006    0.698885
               2007    0.875000
               2008    0.992754
               2009    1.003571
               2010    0.982394
               2011    0.996540
               2012    1.040816
               2013    1.036913
               2014    1.016667
               2015    0.966777
               2016    0.923077
               2017    0.833333
               2018    0.716263
               2019    0.582456
Vietnam        1960    0.000000
               1961    0.000000
               1962    0.000000
               1963    0.000000
               1964    0.000000
               1965    0.000000
               1966    0.000000
               1967    0.000000
               1968    0.000000
               1969    0.000000
               1970    0.000000
               1971    0.000000
               1972    0.000000
               1973    0.000000
               1974    0.000000
               1975    0.000000
               1976    0.000000
               1977    0.000000
               1978    0.000000
               1979    0.000000
               1980    0.000000
               1981    0.000000
               1982    0.000000
               1983    0.000000
               1984    0.000000
               1985    0.000000
               1986    0.000000
               1987    0.000000
               1988    0.000000
               1989    0.000000
               1990    0.000000
               1991    0.000000
               1992    0.000011
               1993    0.000056
               1994    0.000170
               1995    0.000314
               1996    0.000905
               1997    0.002075
               1998    0.002855
               1999    0.004165
               2000    0.009875
               2001    0.015489
               2002    0.023313
               2003    0.033293
               2004    0.059687
               2005    0.114439
               2006    0.223404
               2007    0.526932
               2008    0.868910
               2009    1.127440
               2010    1.272727
               2011    1.428571
               2012    1.469933
               2013    1.365639
               2014    1.483097
               2015    1.294498
               2016    1.292735
               2017    1.268499
               2018    1.476440
               2019    1.409326
Yemen          1960    0.000000
               1961    0.000000
               1962    0.000000
               1963    0.000000
               1964    0.000000
               1965    0.000000
               1966    0.000000
               1967    0.000000
               1968    0.000000
               1969    0.000000
               1970    0.000000
               1971    0.000000
               1972    0.000000
               1973    0.000000
               1974    0.000000
               1975    0.000000
               1976    0.000000
               1977    0.000000
               1978    0.000000
               1979    0.000000
               1980    0.000000
               1981    0.000000
               1982    0.000000
               1983    0.000000
               1984    0.000000
               1985    0.000000
               1986    0.000000
               1987    0.000000
               1988    0.000000
               1989    0.000000
               1990    0.000000
               1991    0.000000
               1992    0.000119
               1993    0.000380
               1994    0.000573
               1995    0.000554
               1996    0.000568
               1997    0.000763
               1998    0.000976
               1999    0.001639
               2000    0.001839
               2001    0.008268
               2002    0.026467
               2003    0.035526
               2004    0.075897
               2005    0.113433
               2006    0.143961
               2007    0.204225
               2008    0.294521
               2009    0.369333
               2010    0.478448
               2011    0.491597
               2012    0.567347
               2013    0.669323
               2014    0.662791
               2015    0.566038
               2016    0.602941
               2017    0.553957
               2018    0.536842
               2019    0.000000
Zambia         1960    0.000000
               1961    0.000000
               1962    0.000000
               1963    0.000000
               1964    0.000000
               1965    0.000000
               1966    0.000000
               1967    0.000000
               1968    0.000000
               1969    0.000000
               1970    0.000000
               1971    0.000000
               1972    0.000000
               1973    0.000000
               1974    0.000000
               1975    0.000000
               1976    0.000000
               1977    0.000000
               1978    0.000000
               1979    0.000000
               1980    0.000000
               1981    0.000000
               1982    0.000000
               1983    0.000000
               1984    0.000000
               1985    0.000000
               1986    0.000000
               1987    0.000000
               1988    0.000000
               1989    0.000000
               1990    0.000000
               1991    0.000000
               1992    0.000000
               1993    0.000000
               1994    0.000000
               1995    0.000170
               1996    0.000291
               1997    0.000474
               1998    0.000837
               1999    0.002792
               2000    0.009510
               2001    0.011308
               2002    0.012636
               2003    0.021327
               2004    0.040000
               2005    0.079832
               2006    0.136066
               2007    0.211200
               2008    0.276562
               2009    0.334091
               2010    0.400735
               2011    0.582857
               2012    0.724138
               2013    0.697987
               2014    0.655844
               2015    0.729560
               2016    0.731707
               2017    0.792899
               2018    0.890805
               2019    0.960894
Zimbabwe       1960    0.000000
               1961    0.000000
               1962    0.000000
               1963    0.000000
               1964    0.000000
               1965    0.000000
               1966    0.000000
               1967    0.000000
               1968    0.000000
               1969    0.000000
               1970    0.000000
               1971    0.000000
               1972    0.000000
               1973    0.000000
               1974    0.000000
               1975    0.000000
               1976    0.000000
               1977    0.000000
               1978    0.000000
               1979    0.000000
               1980    0.000000
               1981    0.000000
               1982    0.000000
               1983    0.000000
               1984    0.000000
               1985    0.000000
               1986    0.000000
               1987    0.000000
               1988    0.000000
               1989    0.000000
               1990    0.000000
               1991    0.000000
               1992    0.000000
               1993    0.000000
               1994    0.000000
               1995    0.000000
               1996    0.000000
               1997    0.000490
               1998    0.001624
               1999    0.014746
               2000    0.022353
               2001    0.026387
               2002    0.028250
               2003    0.030333
               2004    0.035500
               2005    0.053471
               2006    0.069590
               2007    0.100000
               2008    0.133065
               2009    0.319200
               2010    0.606299
               2011    0.713178
               2012    0.961832
               2013    1.014925
               2014    0.867647
               2015    0.927536
               2016    0.921429
               2017    0.992958
               2018    0.895833
               2019    0.904110
dtype: float64

In [175]:
final['Country'].nunique(dropna=False)
final.nunique()
type(final)

pandas.core.frame.DataFrame

In [187]:
#final['Country'].unique()
final.head()
geo_c = pd.Series(geo_codes['geo'])
geo_c.str.upper()

#OR
final2 = final.geo.str.upper()
final2
final['geo'] = final['geo'].str.upper() 
final

       geo g77_and_oecd_countries  ... cell_phones_total population
0      AFG                    g77  ...               0.0    9000000
1      AFG                    g77  ...               0.0    9170000
2      AFG                    g77  ...               0.0    9350000
3      AFG                    g77  ...               0.0    9540000
4      AFG                    g77  ...               0.0    9740000
...    ...                    ...  ...               ...        ...
11635  ZWE                    g77  ...        12800000.0   13800000
11636  ZWE                    g77  ...        12900000.0   14000000
11637  ZWE                    g77  ...        14100000.0   14200000
11638  ZWE                    g77  ...        12900000.0   14400000
11639  ZWE                    g77  ...        13200000.0   14600000

[11640 rows x 24 columns]

**PART FOUR : Process Data**

In [188]:
final.describe()

       iso3166_1_numeric      latitude  ...  cell_phones_total    population
count       11640.000000  11640.000000  ...       1.164000e+04  1.164000e+04
mean          432.463918     18.989542  ...       7.875722e+06  2.710307e+07
std           253.380691     23.879363  ...       5.572496e+07  1.086187e+08
min             4.000000    -42.000000  ...       0.000000e+00  4.380000e+03
25%           212.000000      4.000000  ...       0.000000e+00  1.117500e+06
50%           429.000000     17.191665  ...       0.000000e+00  5.100000e+06
75%           659.000000     40.000000  ...       5.615000e+05  1.590000e+07
max           894.000000     65.000000  ...       1.730000e+09  1.430000e+09

[8 rows x 6 columns]

In [197]:
cellagg['cell_phones_total'].nlargest(5)

Country  year
China    2019    1.730000e+09
         2018    1.650000e+09
         2017    1.470000e+09
         2016    1.360000e+09
         2014    1.290000e+09
Name: cell_phones_total, dtype: float64